import httpx

# 去这注册 https://my.telegram.org/auth?to=apps
API_ID = 1234567
API_HASH = ""

# 去这注册 https://t.me/botfather
BOT_TOKEN = ""

# 原版后端地址
ai_api_url = "http://1.1.1.1/generate-stream"


# httpx_proxy = httpx.Proxy(
#     url="http://127.0.0.1:7890",
# )
httpx_proxy = {}

# bot_proxy = ("http", "127.0.0.1", 7890)
bot_proxy = ()

scale: int = 11
steps: int = 40
default_uc = [
    "bad cameltoe",
    "cloned face",
    "poorly drawn gloves",
    "fused pantie",
    "fused seam",
    "malformed limbs",
    "bad tails",
    "liquid tentacles",
    "bad crotch seam",
    "bad shoes",
    "normal quality",
    "fused ears",
    "liquid body",
    "more than 2 nipples",
    "poorly drawn anus",
    "missing collarbone",
    "bad feet",
    "safety knickers",
    "liquid collarbone",
    "poorly drawn feet",
    "fused thigh gap",
    "excrement",
    "fused calf",
    "colorful tongue",
    "bad gloves",
    "fused shoes",
    "colorful nipples",
    "error",
    "censored",
    "missing thigh gap",
    "blurred",
    "poorly drawn nipples",
    "disappearing arms",
    "more than 1 right hand",
    "poorly drawn hands",
    "liquid thigh gap",
    "malformed",
    "dirty teeth",
    "mutilated",
    "liquid tongue",
    "signature",
    "extra breasts",
    "disappearing legs",
    "more than two shoes",
    "lowres",
    "extra animal ears",
    "fused gloves",
    "one hand with less than 5 digit",
    "heavy animal ears",
    "beard",
    "JPEG artifacts",
    "one hand with more than 5 fingers",
    "3D character",
    "extra limbs",
    "disappearing calf",
    "fused fingers",
    "bad pantie",
    "morbid",
    "jpeg artifacts",
    "extra ears",
    "liquid clit",
    "extra knee",
    "tongue within mouth",
    "thick lips",
    "fused digit",
    "fused anus",
    "disappearing thigh",
    "fused face",
    "bad eyes",
    "poorly drawn tentacles",
    "bad anus",
    "huge breasts",
    "disfigured",
    "watermark",
    "ui",
    "big muscles",
    "different nipples",
    "missing breasts",
    "blurry",
    "one hand with more than 5 digit",
    "missing fingers",
    "bad asshole",
    "fused hairs",
    "black tongue",
    "fused animal ears",
    "fewer digits",
    "duplicate",
    "poorly drawn breasts",
    "fused clit",
    "fused eyes poorly drawn eyes",
    "poorly drawn cloth",
    "bad thigh gap",
    "poorly drawn thigh gap",
    "black nipples",
    "3D game",
    "missing hand",
    "poorly drawn ears",
    "poorly drawn shoes",
    "huge thighs",
    "anatomical nonsense",
    "lowers",
    "(blurry)",
    "bad knee",
    "poorly drawn crotch",
    "poorly drawn cum",
    "liquid breasts",
    "pubic hair",
    "long face",
    "(((missing arms)))",
    "bad proportions",
    "missing nipples",
    "fused nipples",
    "worst quality",
    "extra calf",
    "missing animal ears",
    "bad tongue",
    "big mouth",
    "bad clit",
    "poorly drawn face",
    "heavy breasts",
    "fused cum",
    "more than 1 left hand",
    "poorly drawn mouth",
    "bad breasts",
    "fused tentacles",
    "(mutated hands and fingers:1.5 )",
    "malformed hands",
    "fused hand",
    "missing legs",
    "bad cum",
    "bad crotch",
    "safety panties",
    "huge haunch",
    "bad pussy",
    "deformed",
    "liquid digit",
    "more than 2 legs",
    "malformed feet",
    "too long tongue",
    "fused pussy",
    "faeces",
    "mosaic",
    "text",
    "bad ears",
    "extra shoes",
    "testis",
    "extra feet",
    "obesity",
    "3D",
    "one hand with less than 5 fingers",
    "bad shadow",
    "liquid ears",
    "mutated",
    "poorly drawn hairs",
    "bad face",
    "extra digit",
    "colorful cameltoe",
    "missing digit",
    "missing feet",
    "missing thighs",
    "unnatural body",
    "fused breasts",
    "username",
    "bad hairs",
    "big face",
    "yellow teeth",
    "missing clit",
    "r18g",
    "poorly drawn :1.2)",
    "huge calf",
    "poorly drawn pussy",
    "furry",
    "bad hands",
    "bad collarbone",
    "QR code",
    "gross proportions. short arm",
    "fused collarbone",
    "bad animal ears",
    "low quality",
    "cracked mouth",
    "3D game scene",
    "missing ears",
    "ugly",
    "dirty pantie",
    "multiple breasts",
    "poorly drawn asshole",
    "bar code",
    "bad digit",
    "extra legs",
    "shit",
    "more than 2 thighs",
    "long neck",
    "missing calf",
    "poorly drawn crotch seam",
    "missing limb",
    "cropped",
    "r18",
    "extra arms",
    "bad anatomy",
    "fused asshole",
    "futa",
    "uncoordinated body",
    "fused crotch",
    "nsfw",
    "text font ui",
    "liquid animal ears",
    "fused feet",
    "extra eyes",
    "bad nipples",
    "pony",
    "black-white",
    "mutation",
    "(mutation",
    "fused mouth",
    "colorful clit",
    "strong girl",
    "heavy ears",
    "black clit",
    "missing asshole",
    "fused cloth",
    "poorly drawn animal ears",
    "poorly drawn pantie",
    "bad tentacles",
    "bad mouth",
    "(long body :1.3)",
    "dirty face",
    "split tentacles",
    "extra thighs",
]
